package com.example.luisangel.biorvel.ListaMarvel;

import java.util.ArrayList;

public class ListaSinDescripcion {

    public ArrayList<String> rellenaNombresHeroes(){
        ArrayList<String> lista = new ArrayList<>();
        lista.add("Pepper Potts");
        lista.add("Iron Patriot");
        lista.add("Betty Ross");
        lista.add("Thaddeus Ross");
        lista.add("Black Widow");
        lista.add("Nick Fury");
        lista.add("Odin");
        lista.add("Hawkeye");
        lista.add("Loki");
        lista.add("Winter Soldier");
        lista.add("Maria Hill");
        lista.add("Happy Hogan");
        lista.add("Sharon Carter");
        lista.add("Quick Silver");
        lista.add("Scarlet Witch");
        lista.add("Peter Quill");
        lista.add("Drax");
        lista.add("Groot");
        lista.add("Nebula");
        lista.add("Ant-Man (Scott Lang)");
        lista.add("Black Panther");
        lista.add("Dr. Strange (Marvel: Avengers Alliance)");
        lista.add("Mantis");
        lista.add("Okoye");
        return lista;
    }

    public ArrayList<String> rellenaDescripcionHeroes(){
        ArrayList<String> lista = new ArrayList<>();
        lista.add("She's the Chief Executive Officer of Stark Industries. Originally working as Tony Stark's personal assistant, she would take care of his schedule and perform any task he wished. During this time, she became good friends with Stark; however, both she and Stark had begun developing romantic feelings for each other. Neither was able to act on these feelings, as they each feared that the other would not accept them.");
        lista.add("He's a U.S. military officer and jet pilot in the U.S. Air Force. He is the best friend of Tony Stark/Iron Man and the liaison between Stark Industries and the military in the Department of Acquisitions. When Stark was kidnapped by the Ten Rings, Rhodes led the mission to rescue his friend. He is known as War Machine when wearing his heavily-armed battlesuit but his alias was temporarily rebranded to Iron Patriot during Aldrich Killian's War. ");
        lista.add("She was a scientist and professor at Culver University. She dated Bruce Banner and helped him after a horrible accident involving Gamma Radiation turned him into the Hulk. ");
        lista.add("He's a former Lieutenant General of the United States Army. During his career, he was put in charge of the military project called the Bio-Tech Force Enhancement Project, aiming to recreate the Super Soldier Serum. However, the experiment led to an accident which transformed the scientist Bruce Banner into Hulk.");
        lista.add("She's one of the most talented spies and assassins in the entire world and a founding member of the Avengers. Originally an agent of the Soviet agency for foreign intelligence, the KGB, she later became a member of S.H.I.E.L.D., the international counter-intelligence agency. Having extensive mastery in martial arts and armed with her Widow's Bite, Black Widow became one of S.H.I.E.L.D.'s most efficient agents. During one mission, she was sent undercover into Stark Industries to watch Tony Stark due to fears that he was dying. During this mission, Romanoff had assisted Stark with defeating Ivan Vanko's terrorist plots against him. ");
        lista.add("He was a former officer of the United States Army and an espionage veteran of the CIA during the Cold War. He joined S.H.I.E.L.D., a covert international peacekeeping organization which operates as humanity's first line of defense against Earth's most dangerous enemies. He quickly impressed S.H.I.E.L.D.'s higher-ups and was promoted to the position of Director, becoming the leader of S.H.I.E.L.D. He led S.H.I.E.L.D. for years, spearheading the Avengers Initiative, Project T.A.H.I.T.I., Project Insight, and other operations. ");
        lista.add("He was the former King of Asgard, protector of the Nine Realms, father of Hela and Thor, the adoptive father of Loki, and husband of Frigga. During the ancient times, he was worshiped as the god of wisdom by the inhabitants of Earth. Once the greatest warrior in all the Nine Realms, over the centuries he learned how to appreciate peace, eventually banishing his own daughter to Hel when she attempted to subjugate the entire universe. When Thor almost provoked a new war with the Frost Giants of Jotunheim, Odin stripped him of his powers and exiled him to Earth, leaving Loki to take the throne. Around this time, Odin unexpectedly fell into the Odinsleep, and when Thor had returned and saved the Frost Giants from extinction at the hands of Loki, who seemingly lost his life during the conflict, Odin realized that Thor had proven that he would be worthy enough to take the throne of Asgard. ");
        lista.add("He's a former special agent of S.H.I.E.L.D., where he worked under the supervision of Phil Coulson. Known for his use of the bow and arrow as his primary weapon, Barton became one of S.H.I.E.L.D.'s best agents and assisted in the recruitment of Black Widow, whom he developed a strong friendship with. Assigned by Director Nick Fury to watch over the Tesseract, he was brainwashed by Loki and used as a pawn for his evil schemes. However, following the Attack on the Helicarrier, he was freed from Loki's mental control by Black Widow and joined the Avengers to fight against Loki's alien army in the Battle of New York, ending the Chitauri Invasion before Barton returned to his work as an agent of S.H.I.E.L.D.. ");
        lista.add("He was the biological son of King Laufey, the ruler of the Frost Giants in Jotunheim. Shortly after his birth, Loki was then abandoned and left to die. Found by the Asgardian King Odin, he was taken to Asgard and raised by Odin and his wife Frigga as an Asgardian prince, along with their true biological son Thor. When he grew up, he became known as the \"God of Mischief\". When Thor was to be crowned King, Loki had sabotaged the coronation by letting the Frost Giants attack Asgard, thus leading Thor to seek vengeance on Jotunheim, which resulted in Thor's banishment to Earth and Loki finding out the truth about his heritage. Frigga gave Loki the throne when Odin had fallen into the Odinsleep, however when the Warriors Three and Sif attempted to return Thor home, Loki was forced to try to stop them. Regardless, Thor returned from his exile on Earth and ended Loki's reign. ");
        lista.add("James Buchanan \"Bucky\" Barnes was a former soldier of the 107th Infantry Regiment and the best friend of Steve Rogers, since childhood. Barnes was conscripted and assigned to the 107th in 1942. His regiment was captured by the forces of HYDRA, but Barnes along with what remained of his regiment were rescued by Rogers, who had become Captain America during Barnes' military absence. Joining forces in the continuing war, Barnes and Rogers formed the Howling Commandos to battle the Red Skull's forces. During an attempt to capture HYDRA scientist Arnim Zola, Barnes was caught in an ambush and plummeted hundreds of feet from the HYDRA train. As no body was ever recovered, he was then presumed dead, but officially listed as MIA.");
        lista.add("She was the former Deputy Director of S.H.I.E.L.D., and also held the title of \"Commander\". She enjoyed a well-deserved reputation as tough-minded and by the book. Her clearheaded pragmatism was a valued source of reason during the critical discourse surrounding the Avengers Initiative. After Nick Fury faked his death, she worked with him and was a part of the assault team that took down the Helicarriers from Project Insight. ");
        lista.add("He's Tony Stark's closest friend and chauffeur who formerly worked as his personal bodyguard and Head of Security of Stark Industries. He was almost killed during Aldrich Killian's War, which motivated Stark to get revenge on the Mandarin, who he believed was behind Hogan's injuries. After his recovery, Hogan continued to faithfully serve as Stark's friend and employee. He oversaw Stark's mentorship over Peter Parker/Spider-Man, aiding the young hero on his trip to Germany and acting as their liaison when Parker continued his superhero activities. Hogan, however, was irritated by the boy and avoided his duties with him. After Parker defeated Vulture to prevent the cargo in which Hogan kept certain valuable items to be transferred to the New Avengers Facility from getting hijacked, the young hero earned Hogan’s admiration and respect. ");
        lista.add("She is the great niece of legendary S.H.I.E.L.D. founder Peggy Carter. Following in her aunt's footsteps, Carter became an agent of S.H.I.E.L.D. who had briefly worked undercover as the neighbor of Steve Rogers under the direct orders of Nick Fury. She fought on the side of S.H.I.E.L.D. during the Battle at the Triskelion, facing off against Brock Rumlow to protect millions of lives. In the aftermath of the HYDRA Uprising she was forced to then leave S.H.I.E.L.D. and instead joined the CIA. She continued to have a close relationship with Rogers and sided with him when he chose to protect Bucky Barnes from the government she still worked for, indirectly being responsible for sparking the devastating Avengers Civil War.");
        lista.add("He was a native of the Eastern European country of Sokovia who grew up with his fraternal twin sister, Wanda. The country, which was embroiled in constant war and strife, became the base of operations for a HYDRA cell operated by Wolfgang von Strucker, who recruited Pietro and Wanda to take part in a series of tests involving the Scepter, giving the twins superpowers. While his sister received a number of mental abilities, Pietro acquired the ability to move at supersonic speeds and other physical features. When HYDRA fell, the twins joined the A.I. Ultron to continue their quest for revenge on Tony Stark, but eventually switched sides and helped the Avengers when they discovered Ultron's true intentions. Pietro then fought in the Battle of Sokovia alongside all of the other Avengers, but later sacrificed his own life to protect Hawkeye and a civilian boy named Costel, much to his sister's grief. ");
        lista.add("She was a native of the Eastern European country of Sokovia who grew up with her twin brother, Pietro. In an effort to help purge their country of strife, the twins agreed to undergo experiments with the Scepter under the supervision of Wolfgang von Strucker's HYDRA cell, and received superpowers as a result, with Wanda attaining various abilities including telekinesis, telepathy, and energy manipulation. When HYDRA fell, the twins joined the robot Ultron to get their revenge on Tony Stark, but eventually switched sides and joined the Avengers when they discovered Ultron's true intentions. Although Pietro was killed during the ensuing Ultron Offensive, Wanda survived and became a member of the Avengers. During the Avengers Civil War, she sided with Captain America and was briefly imprisoned in the Raft before Rogers freed her along with his teammates. ");
        lista.add("He was a half-human, half-Celestial who was abducted from Earth by the Yondu Ravager Clan in 1988. After his abduction, he began building fame as the legendary outlaw Star-Lord. In 2014, he decided to leave the Ravagers and operate individually, starting by stealing a precious artifact known as the Orb, unintentionally becoming a key player in the Quest for the Orb. Following his arrest, he forged an uneasy alliance with fellow inmates Gamora, Drax the Destroyer, Rocket Raccoon, and Groot, and formed the Guardians of the Galaxy team with them a short while later in order to stop Ronan the Accuser from destroying Xandar. After the Battle of Xandar, he left with the other Guardians to do \"a little bit of good and a little bit of bad.\"" );
        lista.add("He was a former intergalactic criminal and a member of the Guardians of the Galaxy. He sought revenge on Ronan the Accuser for killing his wife and daughter, and went on a rampage across the galaxy, ending with him being imprisoned by the Nova Corps in the Kyln. There Drax became uneasy allies with Star-Lord, Gamora, Rocket Raccoon, and Groot. Together they broke out of the Kyln and became embroiled in the Quest for the Orb. After the Battle of Xandar, in which he finally exacted his vengeance on Ronan, Drax left Xandar with the other Guardians but not before declaring Thanos as his next target. ");
        lista.add("He was a sentient, tree-like individual and the accomplice of Rocket Raccoon. Together, the pair had traveled the galaxy picking up bounties until they met Star-Lord and Gamora just before the four of them were captured and put into the Kyln, where they also met Drax the Destroyer. There, they agreed to work together to escape and sell the Orb for a massive profit. However, when it was discovered that the Orb contained one of the Infinity Stones which was being sought out by Ronan the Accuser, Groot convinced his friends to risk everything to stop Ronan's diabolical plans. During the Final Battle, Groot sacrificed his own life to save his new friends. However, part of his destroyed body was planted by Rocket to birth a new Groot, as they joined the Guardians of the Galaxy. ");
        lista.add("She's a Luphomoid assassin, an adopted daughter of the intergalactic warlord, Thanos and adopted sister of Gamora. As the right-hand woman of Ronan the Accuser during his and Thanos' quest to retrieve the Orb, she helped him in the fight against the planet Xandar and the Guardians of the Galaxy. She vanished after a fight against her sister. Nebula soon afterwards was captured by the Sovereign and handed back to the Guardians. She escaped and helped Taserface lead the other Ravagers in a mutiny against their former leader Yondu Udonta before leaving to find and kill Gamora. After forgiving and helping her own sister alongside the Guardians during the Battle on Ego's Planet, she left in a ship to pursue a revenge mission against Thanos. ");
        lista.add("He's a former criminal who was convinced by Pym Technologies CEO Hank Pym to take up his mantle as the new Ant-Man. As Ant-Man, Lang fought against Darren Cross, Pym's protégé who became obsessed with Pym Particles and intended to recreate and sell the technology to terrorist organizations such as HYDRA and the Ten Rings. After his daughter, Cassie Lang, was taken hostage by Cross, Lang was able to send both of them into the Quantum Realm, where he saw Pym's wife Janet van Dyne, before successfully returning. Cross was presumably killed. Lang then began a romantic relationship with Pym's daughter, Hope van Dyne.");
        lista.add("He was the monarch of the African nation of Wakanda, and the son of T'Chaka and Ramonda. As the Wakandan monarch, he was also the former holder of the Black Panther mantle. After his father was killed in a bombing attack orchestrated by Helmut Zemo, the new monarch set out to kill the Winter Soldier, who was widely believed to be responsible for the attack. After being drawn into the Avengers Civil War and siding with Iron Man, ");
        lista.add("He was a powerful sorcerer and a leading member of the Masters of the Mystic Arts. Originally a brilliant yet arrogant neurosurgeon, Strange had suffered a car accident, resulting in his hands becoming crippled. When Western medicine failed him, Strange embarked on a journey that led him to Kamar-Taj where Strange had made the discovery of magic and alternate dimensions, being trained by the Ancient One. Though focused on healing his hands, Strange learned more of the mystic arts and helped the Masters prevent Kaecilius from merging Earth with their Dark Dimension, but not before witnessing the Ancient One's death. With the demise of his mentor, Strange became the protector of the New York Sanctum within New York City as well as Earth's protector from any inter-dimensional threats. ");
        lista.add("She was a young empathic woman raised by the Celestial Ego and recruited as a member of the Guardians of the Galaxy. Since she was a child, Mantis helped ease Ego's neurotic behavior with her powers until the Guardians of the Galaxy came to his planet. ");
        return lista;
    }

    public ArrayList<String> rellenaNombresVillanos() {
        ArrayList<String> lista = new ArrayList<>();
        lista.add("Obadiah Stane");
        lista.add("Iron Monger");
        lista.add("Raza");
        lista.add("Mandarin");
        lista.add("Red Skull");
        lista.add("Ronan");
        lista.add("Alexander Pierce");
        lista.add("Baron Strucker");
        lista.add("Korath");
        lista.add("Klaw");
        lista.add("Zemo");
        lista.add("Ancient One");
        lista.add("Mordo");
        lista.add("Dormammu");
        lista.add("Ego");
        lista.add("N'Jadaka");
        return lista;
    }

    public ArrayList<String> rellenaDescripcionVillanos(){
        ArrayList<String> lista = new ArrayList<>();
        lista.add("He was the business partner of Tony Stark and a good friend of his father, Howard Stark. After Howard Stark's death, Stane became interim CEO of Stark Industries until Tony Stark took over officially shortly after. Stane's jealousy of the younger Stark led him to join forces with the Ten Rings to organize a failed attempt to assassinate him so Stane could become CEO once again. When this failed Stane created the Iron Monger Armor and attempted to kill Stark himself, leading to his own death. ");
        lista.add("was a member of the Ten Rings, a terrorist organization, stationed somewhere in Afghanistan. Raza made deals with Obadiah Stane to kidnap Tony Stark in exchange for weapons. However, when Stark escaped, Raza and his soldiers were betrayed and murdered by Stane");
        lista.add("He's a powerful terrorist, who serves as the leader of the Ten Rings, an international terrorist organization. His identity is currently unknown. Though many believed that the Mandarin was just a hoax invented by the scientist Aldrich Killian, the Mandarin is actually quite real. ");
        lista.add("Johann Schmidt is the former head of HYDRA-Abteilung, a special weapons division of the Nazi Schutzstaffel and the modern-day incarnation of the ancient HYDRA society. A brilliant scientist in his own right, he fought his way through the ranks of Nazi elite to become a confidant of Adolf Hitler himself. However, his ambition to become the superior man led him to test an imperfect version of the Super Soldier Serum on himself which transformed him into the horrifying Red Skull. ");
        lista.add("Ronan, also known as Ronan the Accuser was a radical member of the Kree race who was disgusted by a peace treaty made between the Kree Empire and Xandar. A ferocious, genocidal militarist, Ronan attempted to eradicate the Xandarians by forging an alliance with the Mad Titan Thanos, offering the Orb in exchange for the destruction of Xandar. After a long search, Ronan acquired the Orb but, after having seen its true destructive capabilities, decided against giving it to Thanos and chose to take the Orb's power for himself. Using his new-found power, he attacked Xandar, but was defeated and killed by the combined strength of the Guardians of the Galaxy. ");
        lista.add("He was one of HYDRA's leaders and its top undercover operative inside the United States Government, S.H.I.E.L.D., and the World Security Council. He commanded the HYDRA forces within S.H.I.E.L.D., working to create a world so chaotic, that its people would give up their own freedoms willingly. To that end, he created Project Insight, a project that would have given HYDRA absolute control over the world, inciting the HYDRA Uprising. His plan was stopped by Captain America, Black Widow, Falcon, Maria Hill, and Nick Fury during the Battle at the Triskelion, in which he was killed by Director Fury. ");
        lista.add("He was a German Baron and one of the leaders of HYDRA. ");
        lista.add("He was a Kree mercenary working for Ronan the Accuser under the order of Thanos with orders to locate the Orb. He chose to remain loyal to Ronan once the Orb was found and was killed by Drax the Destroyer during the Battle of Xandar. ");
        lista.add("He was a black-market arms dealer, gangster, and international criminal who had worked alongside N'Jobu in order to expose Wakanda to the rest of the world, with Klaue stealing a stockpile of Vibranium as a result in 1992. During an encounter with Ultron thirteen years later, Klaue sold all of his Vibranium to the A.I. before losing his arm during an argument. ");
        lista.add("He is a Sokovian citizen turned terrorist mastermind who sought revenge against the Avengers after losing his family in the Battle of Sokovia, becoming obsessed with defeating and destroying them.");
        lista.add("She was the Sorcerer Supreme as well as the leader of the Masters of the Mystic Arts. ");
        lista.add("He is a former member of the Masters of the Mystic Arts and was a close ally to the Ancient One, assisting her with recruiting and training their new soldiers. ");
        lista.add("He is a primordial, inter-dimensional entity who wields apocalyptic levels of supernatural power and is the ruler of the Dark Dimension. Dormammu convinced Kaecilius to use his power to destroy the Masters of the Mystic Arts and bring the Dark Dimension to Earth. Before Dormammu could complete his plans, he was confronted by Doctor Strange, who used the Eye of Agamotto to trap Dormammu in an endless time loop until he agreed to leave Earth and take Kaecilius with him. ");
        lista.add("He was a Celestial, a primordial and an extremely powerful being, as well as the biological father of Star-Lord. A ruthless, megalomaniacal entity possessing a god complex,");
        lista.add("Erik Stevens (born N'Jadaka) was a former African-American black-ops soldier of Wakandan origin through his father, Prince N'Jobu. His savagery while serving in the U.S. black-ops unit, earned him the nickname Killmonger.");
        return lista;
    }

}
