package com.example.luisangel.biorvel.ListaMarvel;

import com.example.luisangel.biorvel.Personaje;

import java.util.ArrayList;

public class ListaCreadaCero {

    public ArrayList<Personaje> creaPersonajesHeroes(){
        ArrayList<Personaje> lista = new ArrayList<>();
        lista.add(new Personaje("Heimdall","This is the Sentinel Saves everything he sees and hears all of Asgard that sits on the Rainbow Bridge Bifres to monitor any attack on Asgard. In part, he won the role by using his sight to see an army of giants several days away from Asgard, those who have been defeated before reaching Asgard and taking their king prisoner.", "Thor / Thor : Dark world / Avengers : Age of ultron / Thor : Ragnarok / Avengers : Infinity war " ,""));
        lista.add(new Personaje("Volstagg","He is a founding member of the Three Warriors, a trio of adventurous Asgardians and support Thor's cast.","Thor / Thor : Dark world / Thor : Ragnarok","" ));
        lista.add(new Personaje("Hogun","This is one of the founding members of the Three Warriors, an Asgardian trio of adventurers who are part of those who accompany Thor.", "Thor / Thor : Dark world / Thor : Ragnarok",""));
        lista.add(new Personaje("Fandral","He is a founding member of the Three Warriors, a trio of adventurous Asgardians next door with Hogun and Volstagg.", "Thor / Thor : Dark world / Thor : Ragnarok" ,"" ));
        lista.add(new Personaje("Peggy Carter", "Margaret Elizabeth \"Peggy\" Carter was a British officer representing the Strategic Scientific Reserve and Steve Rogers' World War II ally.", "Captain America : The first Avenger / Captain America : Winter soldier ",""));
        lista.add(new Personaje("Phil Coulson","Phil Coulson is the heart of S.H.I.E.L.D, as he works tirelessly to protect the innocent from all kinds of super human threats. He has revered Super Heroes since childhood, and always seeks to uphold their positive legacies", "Avengers / ","" ));
        //lista.add(new Personaje("Harley Kenner" ));
        lista.add(new Personaje("Tyr","He is the Commander of the Einherjar, the Asgardian Army.", "Thor : Dark world / " ,"" ));
        lista.add(new Personaje("Taneleer Tivan","The Collector is known throughout the galaxy as a procurer and curator of rare objects and species thought to be the last of their kind.", "Thor : Dark world / Guardians of the Galaxy vol.1" , ""));
        lista.add(new Personaje("Rhomann Dey", "He was the leader of the Nova Corps of Xandar and one of its few survivors.", "Guardians of the Galaxy vol.1 / ","" ));
        lista.add(new Personaje("Irani Rael","She is the leader of the Nova Corps. She led her people to victory with the help of the Guardians of the Galaxy when Ronan tried to destroy Xandar with a powerful weapon known as the Power Gem.", "Guardians of the Galaxy vol.1 /","" ));
        lista.add(new Personaje("Yondu Udonta","Space pirate Yondu Udonta leads his group of Ravagers across the galaxy, always looking for his next big score. ", "Guardians of the Galaxy vol.1 / Guardians of the Galaxy vol.2" ,""));
        lista.add(new Personaje("Kraglin Obfonteri", "He is the companion of Yondu Udonta and a member of the Devastators.", "Guardians of the Galaxy vol.1 / Guardians of the Galaxy vol.2 ","" ));
        lista.add(new Personaje("Henry Pym","is an entomologist and physicist who developed the Ant-Man suit after discovering the Pym Particles. ", "Ant-Man / Ant-Man and The Wasp " ,"" ));
        lista.add(new Personaje("Hope Van Dyne","is the daughter of Hank Pym and Janet van Dyne. In the end of the first film, she is allowed by her father to assume her mother's identity as the new Wasp. ", "Ant-Man / Ant-Man and the Wasp " ,""  ));
        lista.add(new Personaje("Everett K. Ross", "He is a CIA agent and a former member of the Joint Counter Terrorist Centre.", "Captain America : Civil war / Black Panther " ,"" ));
        lista.add(new Personaje("T'Chaka", "also known as Black Panther, was the king of Wakanda, and the father of T'Challa and Shuri. ", "Captain America : Civil war / Black Panther / " ,""  ));

        lista.add(new Personaje("Stakar Ogord", "He is a legendary Ravager captain and the leader of the Stakar Ravager Clan.","Guardians of the Galaxy vol.1","" ));
        lista.add(new Personaje("Ned Leeds", "He is the best friend of peter parker", "Spider-Man : Homecoming / Avengers : Infinity war " ,"" ));
        lista.add(new Personaje("Valquiria", "She is an Asgardian Valkyrie who was part of an elite group of warriors called the Valkyries.", "Thor : Ragnarok" , ""));
        lista.add(new Personaje("Executioner", "He was an Asgardian warrior who was tasked with becoming the guardian of the Bifrost Bridge by Loki following the banishment of Heimdall. When Loki was revealed to have been ruling Asgard in secret.", "Thor : Ragnarok" ,""  ));
        lista.add(new Personaje("Nakia", "She is a Wakandan spy, T'Challa's lover and a member of the War Dogs", "Black Panther / " ,""  ));
        lista.add(new Personaje("Ramonda", " is the Queen Mother of Wakanda, wife of T'Chaka, and mother of T'Challa and Shuri", "Black Panther / " , "" ));
        lista.add(new Personaje("Zuri", "He was a Wakandan shaman and the trusted loyal adviser to his King", "Black Panther / ","" ));
        lista.add(new Personaje("Shuri","She is the princess of Wakanda and the younger sister of T'Challa.", "Black Panther / Avengers : Infinity war " ,"" ));
        lista.add(new Personaje("M'Baku", "He is the leader of the Jabari Tribe and a member of the Wakandan Tribal Council.", "Black Panther / Avengers : Infinity war " ,"" ));
        lista.add(new Personaje("Eitri", "is the King of the Dwarves, an ancient race of skilled forgers and blacksmiths who hail from the realm of Nidavellir, and its last survivor. ", "Avengers : Infinity war ","" ));
        lista.add(new Personaje("Janet Van Dyne","She was the wife of Hank Pym and the mother of Hope van Dyne. She operated as the superhero Wasp in S.H.I.E.L.D. until she sacrificed herself to save the lives of millions, becoming lost to the Quantum Realm. ", "Ant-Man and the Wasp " , ""  ));
        lista.add(new Personaje("Erik Selvig", "He is an astrophysicist and the teacher of Jane Foster and Darcy Lewis."+
                " He was a Professor of Theoretical Astrophysics at Culver University. While working alongside Foster and Lewis, Selvig encountered an Asgardian named Thor.", "Ant-Man and the Wasp ", ""  ));

        return lista;
    }

    public ArrayList<Personaje> creaPersonajesVillanos(ArrayList<Personaje> lista){

        lista.add(new Personaje("Laufey", "He was the king of the Frost Giants of Jotunheim, and the biological father of Loki.", "Thor" ,"" ));
        lista.add(new Personaje("Destroyer","was an enchanted Asgardian automaton used primarily to guard the Weapon's Vault of Asgard, though it could also be used as a weapon against its master's enemies. ", "Thor","" ));
        lista.add(new Personaje("Aldrich Killian","He was the founder and chief executive officer of Advanced Idea Mechanics. When Tony Stark refused to join him in his research, Killian participated in the development of Extremis thereby amassing a group of Extremis-enhanced soldiers under his command.", "Iron-Man 3","" ));
        lista.add(new Personaje("Maya Hansen","was a scientist working with a fellow colleague Aldrich Killian on the Extremis project. When the project began killing people, Hansen sought Tony Stark's help in fixing it; however, Killian began using the designs for terrorism. When Hansen attempted to stop Killian, she was murdered. ", "Iron-Man 3" ,""  ));
        lista.add(new Personaje("Trevor Slattery", "He was an actor with drug addictions and other legal problems until he was approached by the scientist Aldrich Killian to pose as the Mandarin, the idealized perfect terrorist.", "Iron-Man 3","" ));
        lista.add(new Personaje("Eric Savin","He was a former Lieutenant Colonel of the United States Army. He was the right-hand man of Aldrich Killian and an enemy of Iron Man, using his powers gained by injecting Extremis to seriously endanger Stark's life.", "Iron-Man 3","" ));
        lista.add(new Personaje("Ellen Brandt", " was an agent of A.I.M. and an enemy of Iron Man who had been injected with the Extremis virus, making her a highly dangerous warrior. She was killed by Stark while attempting to capture him. ", "Iron-Man 3","" ));
        lista.add(new Personaje("Jack Taggart", "He was a former US Army soldier who was addicted to Extremis.", "Iron-Man 3","" ));
        lista.add(new Personaje("Malekith", "He was the utterly cruel and malevolent leader of the Dark Elves, a race of beings said to be older than the universe itself.", "Thor : Dark world" ,"" ));
        lista.add(new Personaje("Kurse","He was a lieutenant of the Dark Elves' leader Malekith.", "Thor : Dark world","" ));
        lista.add(new Personaje("Georges Batroc","He is a French-Algerian mercenary, pirate, and martial artist. He is a master of Savate, a traditional French martial art, as well as Kickboxing, using his skills to become one of the world's most wanted men.", "Captain America : Winter soldier","" ));
        lista.add(new Personaje("Darren Cross (Yellowjacket)", "He was the protege of Hank Pym, who usurped his mentor as CEO of Pym Technologies and renamed it Cross Technologies. His obsession with the previous creation of Pym Particles led him to try to replicate his own version, which he then intended to sell to terrorist organizations such as HYDRA and the Ten Rings. Using his own version of Pym's Ant-Man Suit, which was known as Yellowjacket Suit", "Ant-Man",""));
        lista.add(new Personaje("Sonny Burch", "He is a genteel but menacing gangster who dabbles in black-market tech. He has his sights set on controlling Hank Pym's newest piece of technology—and the billions of dollars it will bring him", "Ant-Man and the Wasp",""));
        lista.add(new Personaje("Kaecilius","He is a sorcerer and a former member of the Masters of the Mystic Arts who became disillusioned with the Ancient One when he felt his mentor was not allowing other dimensions to come to Earth, which he believed could then reunite him with his deceased wife and son. He formed the Zealots with the intention of defeating the Ancient One and bringing the inter-dimensional being known as Dormammu to Earth, but was challenged by his former brothers-in-arms as well as a new Master, "+
                "Doctor Strange. He was defeated and became part of the Dark Dimension for all eternity, gaining him the immortality he had desired, but at a horrific cost that he had refused to understand.","Doctor Strange",""));
        lista.add(new Personaje("Taserface","He was a Ravager mercenary and a lieutenant in the Yondu Ravager Clan.", "Guardians of the Galaxy vol.2",""));
        lista.add(new Personaje("Mac Gargan", "He is a professional criminal and one of Adrian Toomes' potential buyers. In the wake of an encounter with Spider-Man, Gargan vowed revenge against the wall-crawler, seeking out new allies to help him kill Spider-Man.","Spider-Man : Homecoming", ""));
        lista.add(new Personaje("Ayesha", "She is the Golden High Priestess of the Sovereign. She was brought into conflict with the Guardians of the Galaxy as a result of Rocket Raccoon stealing from her people. Having failed to destroy the Guardians herself, Ayesha hired Yondu Udonta and his own band of Ravagers to complete the task, only to be betrayed. With information gained from Taserface, Ayesha's army tried again to kill the Guardians during their battle against Ego, only to fail once again, forcing Ayesha to create Adam Warlock as their greatest weapon to finally get their revenge against the Guardians. ","Guardians of the Galaxy vol.2 ","" ));
        lista.add(new Personaje("Jackson Brice","He was a member of Adrian Toomes' criminal group who used modified weaponry, including a gauntlet, to showcase and sell alien-human hybrid weaponry under the alias of Shocker. ", "Spider-Man : Homecoming" ,"" ));
        lista.add(new Personaje("Hela","She was the Asgardian Goddess of Death and the former Executioner of Asgard. Imprisoned in Hel for millennia by her father Odin, Hela was released from her prison following his death and went to restore her power over Asgard, while simultaneously engaging in a series of encounters with her younger brothers Thor and Loki. Gaining power from Asgard, Hela planned to rule Asgard and create an Asgardian Empire. was the Asgardian Goddess of Death and the former Executioner of Asgard. Imprisoned in Hel for millennia by her father Odin, Hela was released from her prison following his death and went to restore her power over Asgard, while simultaneously engaging in a series of encounters with her younger brothers Thor and Loki. Gaining power from Asgard, Hela planned to rule Asgard and create an Asgardian Empire. was the Asgardian Goddess of Death and the former Executioner of Asgard. Imprisoned in Hel for millennia by her father Odin, Hela was released from her prison following his death and went to restore her power over Asgard, while simultaneously engaging in a series of encounters with her younger brothers Thor and Loki. Gaining power from Asgard, Hela planned to rule Asgard and create an Asgardian Empire. ", "Thor : Ragnarok","" ));
        lista.add(new Personaje("Surtur","He was the fire demon and ruler of Muspelheim. Prophesied to be the one to initiate the Asgardian doomsday known as Ragnarok, ", "Thor : Ragnarok","" ));
        lista.add(new Personaje("W'Kabi","He is the former head of security for Wakanda’s Border Tribe as well as T'Challa's best friend. Having lost his faith in his king due to his failure to capture Ulysses Klaue, the man who was responsible for the death of his parents, W'Kabi put his support in Erik Killmonger, allowing him to take the throne of Wakanda and seemingly kill T'Challa as a result. When Black Panther returned to challenge Killmonger, W'Kabi led the fight against his former friend and M'Baku, leading to him being forced by Okoye to surrender. ", "Black Panther",""));
        lista.add(new Personaje("Winter Soldier","James Buchanan \"Bucky\" Barnes was a former soldier of the 107th Infantry Regiment and the best friend of Steve Rogers, since childhood. Barnes was conscripted and assigned to the 107th in 1942. His regiment was captured by the forces of HYDRA, but Barnes along with what remained of his regiment were rescued by Rogers, who had become Captain America during Barnes' military absence. Joining forces in the continuing war, Barnes and Rogers formed the Howling Commandos to battle the Red Skull's forces. During an attempt to capture HYDRA scientist Arnim Zola, Barnes was caught in an ambush and plummeted hundreds of feet from the HYDRA train. As no body was ever recovered, he was then presumed dead, but officially listed as MIA.", "Captain America : The first Avenger / Captain America : Winter soldier / Captain America : Civil war / Black Panther / Avengers : Infinity war ","" ));
        lista.add(new Personaje("Cull Obsidian","He was the strongest of Thanos's children and a member of the Black Order. He joined Thanos in his quest to obtain all the Infinity Stones. He fought in the Battle of Wakanda, where he was killed by Bruce Banner in a Hulkbuster suit.","Avengers : Infinity war", ""));
        lista.add(new Personaje("Corvus Glaive","He was one of Thanos's children and a member of the Black Order. He joined his father in his quest for the six Infinity Stones, initially attacked the Statesman with his siblings and helped to kill the Asgardians aboard and retrieve the Space Stone. He later attacked Vision and Scarlet Witch, almost killing them until the arrival of Captain America, Falcon and Black Widow. Widow wounded him and he and Proxima Midnight were forced to flee. He later hunted the wounded Vision after Midnight told the Avengers he had died from his wounds. He attacked Vision and then Captain America, but Vision stabbed him with his own weapon from behind, killing him. ", "Avengers : Infinity war", ""));
        lista.add(new Personaje("Ebony Maw","He was a member of the Black Order. Gifted with powers of telekinesis, Maw was deeply loyal to Thanos and gave warnings of his power across the galaxy while assisting in the search for the Infinity Stones. Having assisted with wiping out half the Asgardians, both Maw and Cull Obsidian were instructed to locate the Time Stone, leading to Maw capturing Doctor Strange and torturing him in order to obtain the Stone. However, Iron Man and Spider-Man rescued Strange and ejected Maw from his ship into outer space, leaving the Child of Thanos to freeze to death. ", "Avengers : Infinity war", ""));
        lista.add(new Personaje("Ava Starr(Ghost)","She is the daughter of Elihas and Catherine Starr, who gained the ability to render herself intangible and generate extreme amounts of power following a quantum accident, which killed her parents. At a young age, S.H.I.E.L.D. began taking advantage of her powers, enlisting her as a stealth operative under the moniker of Ghost prior to the HYDRA Uprising. Under Bill Foster's care, Ava realizes that she is slowly dying due to a lack of quantum energy, which she involuntarily harnesses.", "Ant-Man and the Wasp", ""));
        lista.add(new Personaje("Proxima Midnight ","She was one of Thanos' children and a member of the Black Order. She and her siblings were essential in his mission to find and harness the power of the Infinity Stones. She fought in the Battle of Wakanda, where she was killed by Scarlet Witch. ", "Avengers : Infinity war", "" ));
        lista.add(new Personaje("Bill Foster","is a biochemist and Berkeley professor who previously worked with Hank Pym on Project G.O.L.I.A.T.H. ", "Ant-Man and the Wasp ",""));
        return lista;
    }
}
